//
// Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
//
// On Thu Jul 18 14:51:21 BST 2019
//
//
// Ports:
// Name                         I/O  size props
// wrap64_nullWithAddr            O    93
// wrap64_nullWithAddr_addr       I    32
//
// Combinational paths from inputs to outputs:
//   wrap64_nullWithAddr_addr -> wrap64_nullWithAddr
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_nullWithAddr(wrap64_nullWithAddr_addr,
				  wrap64_nullWithAddr);
  // value method wrap64_nullWithAddr
  input  [31 : 0] wrap64_nullWithAddr_addr;
  output [92 : 0] wrap64_nullWithAddr;

  // signals for module outputs
  wire [92 : 0] wrap64_nullWithAddr;

  // remaining internal signals
  wire [33 : 0] ret_address__h117;
  wire [7 : 0] ret_addrBits__h118;

  // value method wrap64_nullWithAddr
  assign wrap64_nullWithAddr =
	     { 1'd0,
	       ret_address__h117,
	       ret_addrBits__h118,
	       50'h0001F690003F0 } ;

  // remaining internal signals
  assign ret_addrBits__h118 = { 2'd0, wrap64_nullWithAddr_addr[31:26] } ;
  assign ret_address__h117 = { 2'd0, wrap64_nullWithAddr_addr } ;
endmodule  // module_wrap64_nullWithAddr

