//
// Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
//
// On Thu Jul 18 14:51:20 BST 2019
//
//
// Ports:
// Name                         I/O  size props
// wrap64_isSentry                O     1
// wrap64_isSentry_cap            I    93
//
// Combinational paths from inputs to outputs:
//   wrap64_isSentry_cap -> wrap64_isSentry
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_isSentry(wrap64_isSentry_cap,
			      wrap64_isSentry);
  // value method wrap64_isSentry
  input  [92 : 0] wrap64_isSentry_cap;
  output wrap64_isSentry;

  // signals for module outputs
  wire wrap64_isSentry;

  // value method wrap64_isSentry
  assign wrap64_isSentry = wrap64_isSentry_cap[36:33] == 4'd14 ;
endmodule  // module_wrap64_isSentry

