//
// Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
//
// On Thu Jul 18 14:51:21 BST 2019
//
//
// Ports:
// Name                         I/O  size props
// wrap64_almightyCap             O    93 const
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_almightyCap(wrap64_almightyCap);
  // value method wrap64_almightyCap
  output [92 : 0] wrap64_almightyCap;

  // signals for module outputs
  wire [92 : 0] wrap64_almightyCap;

  // value method wrap64_almightyCap
  assign wrap64_almightyCap = 93'h100000000003FFDF690003F0 ;
endmodule  // module_wrap64_almightyCap

