//
// Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
//
// On Thu Jul 18 14:51:20 BST 2019
//
//
// Ports:
// Name                         I/O  size props
// wrap64_getFlags                O     1
// wrap64_getFlags_cap            I    93
//
// Combinational paths from inputs to outputs:
//   wrap64_getFlags_cap -> wrap64_getFlags
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_getFlags(wrap64_getFlags_cap,
			      wrap64_getFlags);
  // value method wrap64_getFlags
  input  [92 : 0] wrap64_getFlags_cap;
  output wrap64_getFlags;

  // signals for module outputs
  wire wrap64_getFlags;

  // value method wrap64_getFlags
  assign wrap64_getFlags = wrap64_getFlags_cap[37] ;
endmodule  // module_wrap64_getFlags

