//
// Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
//
// On Thu Jul 18 14:51:21 BST 2019
//
//
// Ports:
// Name                         I/O  size props
// wrap64_nullCap                 O    93 const
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_nullCap(wrap64_nullCap);
  // value method wrap64_nullCap
  output [92 : 0] wrap64_nullCap;

  // signals for module outputs
  wire [92 : 0] wrap64_nullCap;

  // value method wrap64_nullCap
  assign wrap64_nullCap = 93'h000000000000001F690003F0 ;
endmodule  // module_wrap64_nullCap

