//
// Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
//
// On Thu Jul 18 14:51:20 BST 2019
//
//
// Ports:
// Name                         I/O  size props
// wrap64_setHardPerms            O    93
// wrap64_setHardPerms_cap        I    93
// wrap64_setHardPerms_hardperms  I    12
//
// Combinational paths from inputs to outputs:
//   (wrap64_setHardPerms_cap,
//    wrap64_setHardPerms_hardperms) -> wrap64_setHardPerms
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_setHardPerms(wrap64_setHardPerms_cap,
				  wrap64_setHardPerms_hardperms,
				  wrap64_setHardPerms);
  // value method wrap64_setHardPerms
  input  [92 : 0] wrap64_setHardPerms_cap;
  input  [11 : 0] wrap64_setHardPerms_hardperms;
  output [92 : 0] wrap64_setHardPerms;

  // signals for module outputs
  wire [92 : 0] wrap64_setHardPerms;

  // value method wrap64_setHardPerms
  assign wrap64_setHardPerms =
	     { wrap64_setHardPerms_cap[92:50],
	       wrap64_setHardPerms_hardperms,
	       wrap64_setHardPerms_cap[37:0] } ;
endmodule  // module_wrap64_setHardPerms

