//
// Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
//
// On Thu Jul 18 14:51:20 BST 2019
//
//
// Ports:
// Name                         I/O  size props
// wrap64_getKind                 O     3
// wrap64_getKind_cap             I    93
//
// Combinational paths from inputs to outputs:
//   wrap64_getKind_cap -> wrap64_getKind
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_getKind(wrap64_getKind_cap,
			     wrap64_getKind);
  // value method wrap64_getKind
  input  [92 : 0] wrap64_getKind_cap;
  output [2 : 0] wrap64_getKind;

  // signals for module outputs
  reg [2 : 0] wrap64_getKind;

  // value method wrap64_getKind
  always@(wrap64_getKind_cap)
  begin
    case (wrap64_getKind_cap[36:33])
      4'd14: wrap64_getKind = 3'd1;
      4'd15: wrap64_getKind = 3'd0;
      default: wrap64_getKind =
		   (wrap64_getKind_cap[36:33] <= 4'd12) ? 3'd4 : 3'd2;
    endcase
  end
endmodule  // module_wrap64_getKind

