//
// Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
//
// On Thu Jul 18 14:51:21 BST 2019
//
//
// Ports:
// Name                         I/O  size props
// wrap64_validAsType             O     1
// wrap64_validAsType_dummy       I    93 unused
// wrap64_validAsType_checkType   I    32
//
// Combinational paths from inputs to outputs:
//   wrap64_validAsType_checkType -> wrap64_validAsType
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_validAsType(wrap64_validAsType_dummy,
				 wrap64_validAsType_checkType,
				 wrap64_validAsType);
  // value method wrap64_validAsType
  input  [92 : 0] wrap64_validAsType_dummy;
  input  [31 : 0] wrap64_validAsType_checkType;
  output wrap64_validAsType;

  // signals for module outputs
  wire wrap64_validAsType;

  // value method wrap64_validAsType
  assign wrap64_validAsType = wrap64_validAsType_checkType <= 32'd12 ;
endmodule  // module_wrap64_validAsType

