//
// Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
//
// On Thu Jul 18 14:51:20 BST 2019
//
//
// Ports:
// Name                         I/O  size props
// wrap64_setType                 O    94
// wrap64_setType_cap             I    93
// wrap64_setType_otype           I     4
//
// Combinational paths from inputs to outputs:
//   (wrap64_setType_cap, wrap64_setType_otype) -> wrap64_setType
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_setType(wrap64_setType_cap,
			     wrap64_setType_otype,
			     wrap64_setType);
  // value method wrap64_setType
  input  [92 : 0] wrap64_setType_cap;
  input  [3 : 0] wrap64_setType_otype;
  output [93 : 0] wrap64_setType;

  // signals for module outputs
  wire [93 : 0] wrap64_setType;

  // value method wrap64_setType
  assign wrap64_setType =
	     { 1'd1,
	       wrap64_setType_cap[92:37],
	       wrap64_setType_otype,
	       wrap64_setType_cap[32:0] } ;
endmodule  // module_wrap64_setType

