//
// Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
//
// On Thu Jul 18 14:51:20 BST 2019
//
//
// Ports:
// Name                         I/O  size props
// wrap64_getOffset               O    32
// wrap64_getOffset_cap           I    93
//
// Combinational paths from inputs to outputs:
//   wrap64_getOffset_cap -> wrap64_getOffset
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wrap64_getOffset(wrap64_getOffset_cap,
			       wrap64_getOffset);
  // value method wrap64_getOffset
  input  [92 : 0] wrap64_getOffset_cap;
  output [31 : 0] wrap64_getOffset;

  // signals for module outputs
  wire [31 : 0] wrap64_getOffset;

  // remaining internal signals
  wire [33 : 0] in__h173, x__h191, y__h190;
  wire [31 : 0] x__h64, x__h66;
  wire [9 : 0] base__h51, offset__h52;

  // value method wrap64_getOffset
  assign wrap64_getOffset = x__h64 | in__h173[31:0] ;

  // remaining internal signals
  assign base__h51 =
	     { wrap64_getOffset_cap[1:0], wrap64_getOffset_cap[17:10] } ;
  assign in__h173 = wrap64_getOffset_cap[91:58] & y__h190 ;
  assign offset__h52 = { 2'd0, wrap64_getOffset_cap[57:50] } - base__h51 ;
  assign x__h191 = 34'h3FFFFFFFF << wrap64_getOffset_cap[31:26] ;
  assign x__h64 = x__h66 << wrap64_getOffset_cap[31:26] ;
  assign x__h66 = { {22{offset__h52[9]}}, offset__h52 } ;
  assign y__h190 = ~x__h191 ;
endmodule  // module_wrap64_getOffset

